#!/bin/sh
for dir in `ls -1 ../locale/`
do
echo "Executing msgfmt -o ../locale/$dir/LC_MESSAGES/directory.mo ../locale/$dir/LC_MESSAGES/directory.po"
msgfmt -o ../locale/$dir/LC_MESSAGES/directory.mo ../locale/$dir/LC_MESSAGES/directory.po
done
