#!/bin/sh
for dir in `ls -1 ../locale/`
do
	mv ../locale/$dir/LC_MESSAGES/useracl.po ../locale/$dir/LC_MESSAGES/useracl.po.bak
	echo "Executing: msgmerge ../locale/$dir/LC_MESSAGES/useracl.po.bak useracl.pot > ../locale/$dir/LC_MESSAGES/useracl.po";
	msgmerge ../locale/$dir/LC_MESSAGES/useracl.po.bak useracl.pot > ../locale/$dir/LC_MESSAGES/useracl.po
done

     
