#!/bin/sh
for dir in `ls -1 ../locale/`
do
echo "Executing msgfmt -o ../locale/$dir/LC_MESSAGES/useracl.mo ../locale/$dir/LC_MESSAGES/useracl.po"
msgfmt -o ../locale/$dir/LC_MESSAGES/useracl.mo ../locale/$dir/LC_MESSAGES/useracl.po
done
