#!/bin/sh
for dir in `ls -1 ../locale/`
do
	mv ../locale/$dir/LC_MESSAGES/junkfolder.po ../locale/$dir/LC_MESSAGES/junkfolder.po.bak
	echo "Executing: msgmerge ../locale/$dir/LC_MESSAGES/junkfolder.po.bak junkfolder.pot > ../locale/$dir/LC_MESSAGES/junkfolder.po";
	msgmerge ../locale/$dir/LC_MESSAGES/junkfolder.po.bak junkfolder.pot > ../locale/$dir/LC_MESSAGES/junkfolder.po
done

     
