#!/bin/sh
for dir in `ls -1 ../locale/`
do
echo "Executing msgfmt -o ../locale/$dir/LC_MESSAGES/ldapfolderinfo.mo ../locale/$dir/LC_MESSAGES/ldapfolderinfo.po"
msgfmt -o ../locale/$dir/LC_MESSAGES/ldapfolderinfo.mo ../locale/$dir/LC_MESSAGES/ldapfolderinfo.po
done
