#!/bin/sh
for dir in `ls -1 ../locale/?????`
do
echo "Executing msgfmt -o ../locale/$dir/LC_MESSAGES/ldapudidentities.mo ../locale/$dir/LC_MESSAGES/ldapudidentities.po"
msgfmt -o ../locale/$dir/LC_MESSAGES/ldapudidentities.mo ../locale/$dir/LC_MESSAGES/ldapudidentities.po
done
