#!/bin/sh
for dir in `ls -1 ../locale/`
do
echo "Executing msgfmt -o ../locale/$dir/LC_MESSAGES/junkfolder.mo ../locale/$dir/LC_MESSAGES/junkfolder.po"
msgfmt -o ../locale/$dir/LC_MESSAGES/junkfolder.mo ../locale/$dir/LC_MESSAGES/junkfolder.po
done
